// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"database/sql"
	"time"
)

type Inventory struct {
	SkuID     int64     `json:"sku_id"`
	Total     int64     `json:"total"`
	Available int64     `json:"available"`
	Locked    int64     `json:"locked"`
	Sold      int64     `json:"sold"`
	Version   int64     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type InventoryDeduction struct {
	ID               int64          `json:"id"`
	RequestID        string         `json:"request_id"`
	SkuID            int64          `json:"sku_id"`
	Quantity         int64          `json:"quantity"`
	Status           string         `json:"status"`
	ReleaseRequestID sql.NullString `json:"release_request_id"`
	ConfirmRequestID sql.NullString `json:"confirm_request_id"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}
