// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	ConfirmInventory(ctx context.Context, arg ConfirmInventoryParams) (Inventory, error)
	CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error)
	DeductInventory(ctx context.Context, arg DeductInventoryParams) (Inventory, error)
	EditInventory(ctx context.Context, arg EditInventoryParams) (Inventory, error)
	GetDeductionByRequestID(ctx context.Context, requestID string) (InventoryDeduction, error)
	GetInventory(ctx context.Context, skuID int64) (Inventory, error)
	InsertDeduction(ctx context.Context, arg InsertDeductionParams) (InventoryDeduction, error)
	LockDeductionByRequestID(ctx context.Context, requestID string) (InventoryDeduction, error)
	MarkDeductionConfirmed(ctx context.Context, arg MarkDeductionConfirmedParams) (InventoryDeduction, error)
	MarkDeductionReleased(ctx context.Context, arg MarkDeductionReleasedParams) (InventoryDeduction, error)
	ReleaseInventory(ctx context.Context, arg ReleaseInventoryParams) (Inventory, error)
}

var _ Querier = (*Queries)(nil)
