// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	ConfirmInventory(ctx context.Context, arg ConfirmInventoryParams) (ConfirmInventoryRow, error)
	ConfirmLockedInventory(ctx context.Context, arg ConfirmLockedInventoryParams) (ConfirmLockedInventoryRow, error)
	CreateInventory(ctx context.Context, arg CreateInventoryParams) (CreateInventoryRow, error)
	DeductInventory(ctx context.Context, arg DeductInventoryParams) (DeductInventoryRow, error)
	DeductLockedInventory(ctx context.Context, arg DeductLockedInventoryParams) (DeductLockedInventoryRow, error)
	EditInventory(ctx context.Context, arg EditInventoryParams) (EditInventoryRow, error)
	GetDeductionByRequestID(ctx context.Context, requestID string) (InventoryDeduction, error)
	GetInventory(ctx context.Context, skuID int64) (GetInventoryRow, error)
	InsertDeduction(ctx context.Context, arg InsertDeductionParams) (InventoryDeduction, error)
	LockDeductionByRequestID(ctx context.Context, requestID string) (InventoryDeduction, error)
	LockRedisBucketStock(ctx context.Context, arg LockRedisBucketStockParams) (LockRedisBucketStockRow, error)
	MarkDeductionConfirmed(ctx context.Context, arg MarkDeductionConfirmedParams) (InventoryDeduction, error)
	MarkDeductionReleased(ctx context.Context, arg MarkDeductionReleasedParams) (InventoryDeduction, error)
	ReleaseInventory(ctx context.Context, arg ReleaseInventoryParams) (ReleaseInventoryRow, error)
	ReleaseLockedInventory(ctx context.Context, arg ReleaseLockedInventoryParams) (ReleaseLockedInventoryRow, error)
}

var _ Querier = (*Queries)(nil)
