// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"database/sql"
)

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventories (sku_id, total, available, locked, sold)
VALUES ($1, $2, $2, 0, 0)
ON CONFLICT (sku_id) DO UPDATE
SET total = EXCLUDED.total,
    available = EXCLUDED.total - inventories.locked - inventories.sold,
    version = inventories.version + 1,
    updated_at = now()
WHERE EXCLUDED.total >= inventories.locked + inventories.sold
RETURNING sku_id, total, available, locked, sold, version, created_at, updated_at
`

type CreateInventoryParams struct {
	SkuID int64 `json:"sku_id"`
	Total int64 `json:"total"`
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, createInventory, arg.SkuID, arg.Total)
	var i Inventory
	err := row.Scan(&i.SkuID, &i.Total, &i.Available, &i.Locked, &i.Sold, &i.Version, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getInventory = `-- name: GetInventory :one
SELECT sku_id, total, available, locked, sold, version, created_at, updated_at FROM inventories WHERE sku_id = $1
`

func (q *Queries) GetInventory(ctx context.Context, skuID int64) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventory, skuID)
	var i Inventory
	err := row.Scan(&i.SkuID, &i.Total, &i.Available, &i.Locked, &i.Sold, &i.Version, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deductInventory = `-- name: DeductInventory :one
UPDATE inventories SET available = available - $2, locked = locked + $2, version = version + 1, updated_at = now()
WHERE sku_id = $1 AND available >= $2
RETURNING sku_id, total, available, locked, sold, version, created_at, updated_at
`

type DeductInventoryParams struct {
	SkuID    int64 `json:"sku_id"`
	Quantity int64 `json:"quantity"`
}

func (q *Queries) DeductInventory(ctx context.Context, arg DeductInventoryParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, deductInventory, arg.SkuID, arg.Quantity)
	var i Inventory
	err := row.Scan(&i.SkuID, &i.Total, &i.Available, &i.Locked, &i.Sold, &i.Version, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const insertDeduction = `-- name: InsertDeduction :one
INSERT INTO inventory_deductions (request_id, sku_id, quantity, status) VALUES ($1, $2, $3, 'LOCKED')
RETURNING id, request_id, sku_id, quantity, status, release_request_id, confirm_request_id, created_at, updated_at
`

type InsertDeductionParams struct {
	RequestID string `json:"request_id"`
	SkuID     int64  `json:"sku_id"`
	Quantity  int64  `json:"quantity"`
}

func (q *Queries) InsertDeduction(ctx context.Context, arg InsertDeductionParams) (InventoryDeduction, error) {
	row := q.db.QueryRowContext(ctx, insertDeduction, arg.RequestID, arg.SkuID, arg.Quantity)
	var d InventoryDeduction
	err := row.Scan(&d.ID, &d.RequestID, &d.SkuID, &d.Quantity, &d.Status, &d.ReleaseRequestID, &d.ConfirmRequestID, &d.CreatedAt, &d.UpdatedAt)
	return d, err
}

const getDeductionByRequestID = `-- name: GetDeductionByRequestID :one
SELECT id, request_id, sku_id, quantity, status, release_request_id, confirm_request_id, created_at, updated_at FROM inventory_deductions WHERE request_id = $1
`

func (q *Queries) GetDeductionByRequestID(ctx context.Context, requestID string) (InventoryDeduction, error) {
	return scanDeduction(q.db.QueryRowContext(ctx, getDeductionByRequestID, requestID))
}

const lockDeductionByRequestID = `-- name: LockDeductionByRequestID :one
SELECT id, request_id, sku_id, quantity, status, release_request_id, confirm_request_id, created_at, updated_at FROM inventory_deductions WHERE request_id = $1 FOR UPDATE
`

func (q *Queries) LockDeductionByRequestID(ctx context.Context, requestID string) (InventoryDeduction, error) {
	return scanDeduction(q.db.QueryRowContext(ctx, lockDeductionByRequestID, requestID))
}

func scanDeduction(row *sql.Row) (InventoryDeduction, error) {
	var d InventoryDeduction
	err := row.Scan(&d.ID, &d.RequestID, &d.SkuID, &d.Quantity, &d.Status, &d.ReleaseRequestID, &d.ConfirmRequestID, &d.CreatedAt, &d.UpdatedAt)
	return d, err
}

const releaseInventory = `-- name: ReleaseInventory :one
UPDATE inventories SET available = available + $2, locked = locked - $2, version = version + 1, updated_at = now()
WHERE sku_id = $1 AND locked >= $2
RETURNING sku_id, total, available, locked, sold, version, created_at, updated_at
`

type ReleaseInventoryParams struct {
	SkuID    int64 `json:"sku_id"`
	Quantity int64 `json:"quantity"`
}

func (q *Queries) ReleaseInventory(ctx context.Context, arg ReleaseInventoryParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, releaseInventory, arg.SkuID, arg.Quantity)
	var i Inventory
	err := row.Scan(&i.SkuID, &i.Total, &i.Available, &i.Locked, &i.Sold, &i.Version, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const markDeductionReleased = `-- name: MarkDeductionReleased :one
UPDATE inventory_deductions SET status = 'RELEASED', release_request_id = $2, updated_at = now()
WHERE request_id = $1 AND status = 'LOCKED'
RETURNING id, request_id, sku_id, quantity, status, release_request_id, confirm_request_id, created_at, updated_at
`

type MarkDeductionReleasedParams struct {
	RequestID        string         `json:"request_id"`
	ReleaseRequestID sql.NullString `json:"release_request_id"`
}

func (q *Queries) MarkDeductionReleased(ctx context.Context, arg MarkDeductionReleasedParams) (InventoryDeduction, error) {
	return scanDeduction(q.db.QueryRowContext(ctx, markDeductionReleased, arg.RequestID, arg.ReleaseRequestID))
}

const confirmInventory = `-- name: ConfirmInventory :one
UPDATE inventories SET locked = locked - $2, sold = sold + $2, version = version + 1, updated_at = now()
WHERE sku_id = $1 AND locked >= $2
RETURNING sku_id, total, available, locked, sold, version, created_at, updated_at
`

type ConfirmInventoryParams struct {
	SkuID    int64 `json:"sku_id"`
	Quantity int64 `json:"quantity"`
}

func (q *Queries) ConfirmInventory(ctx context.Context, arg ConfirmInventoryParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, confirmInventory, arg.SkuID, arg.Quantity)
	var i Inventory
	err := row.Scan(&i.SkuID, &i.Total, &i.Available, &i.Locked, &i.Sold, &i.Version, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const markDeductionConfirmed = `-- name: MarkDeductionConfirmed :one
UPDATE inventory_deductions SET status = 'CONFIRMED', confirm_request_id = $2, updated_at = now()
WHERE request_id = $1 AND status = 'LOCKED'
RETURNING id, request_id, sku_id, quantity, status, release_request_id, confirm_request_id, created_at, updated_at
`

type MarkDeductionConfirmedParams struct {
	RequestID        string         `json:"request_id"`
	ConfirmRequestID sql.NullString `json:"confirm_request_id"`
}

func (q *Queries) MarkDeductionConfirmed(ctx context.Context, arg MarkDeductionConfirmedParams) (InventoryDeduction, error) {
	return scanDeduction(q.db.QueryRowContext(ctx, markDeductionConfirmed, arg.RequestID, arg.ConfirmRequestID))
}

const editInventory = `-- name: EditInventory :one
UPDATE inventories SET total = $2, available = $2 - locked - sold, version = version + 1, updated_at = now()
WHERE sku_id = $1 AND version = $3 AND $2 >= locked + sold
RETURNING sku_id, total, available, locked, sold, version, created_at, updated_at
`

type EditInventoryParams struct {
	SkuID   int64 `json:"sku_id"`
	Total   int64 `json:"total"`
	Version int64 `json:"version"`
}

func (q *Queries) EditInventory(ctx context.Context, arg EditInventoryParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, editInventory, arg.SkuID, arg.Total, arg.Version)
	var i Inventory
	err := row.Scan(&i.SkuID, &i.Total, &i.Available, &i.Locked, &i.Sold, &i.Version, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
