// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: inventory/v1/inventory.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Inventory_CreateOrReplaceInventory_FullMethodName = "/inventory.v1.Inventory/CreateOrReplaceInventory"
	Inventory_DeductInventory_FullMethodName          = "/inventory.v1.Inventory/DeductInventory"
	Inventory_IncreaseInventory_FullMethodName        = "/inventory.v1.Inventory/IncreaseInventory"
	Inventory_ConfirmInventory_FullMethodName         = "/inventory.v1.Inventory/ConfirmInventory"
	Inventory_EditInventory_FullMethodName            = "/inventory.v1.Inventory/EditInventory"
	Inventory_GetInventory_FullMethodName             = "/inventory.v1.Inventory/GetInventory"
)

// InventoryClient is the client API for Inventory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryClient interface {
	CreateOrReplaceInventory(ctx context.Context, in *CreateOrReplaceInventoryRequest, opts ...grpc.CallOption) (*InventoryReply, error)
	DeductInventory(ctx context.Context, in *DeductInventoryRequest, opts ...grpc.CallOption) (*InventoryOperationReply, error)
	IncreaseInventory(ctx context.Context, in *IncreaseInventoryRequest, opts ...grpc.CallOption) (*InventoryOperationReply, error)
	ConfirmInventory(ctx context.Context, in *ConfirmInventoryRequest, opts ...grpc.CallOption) (*InventoryOperationReply, error)
	EditInventory(ctx context.Context, in *EditInventoryRequest, opts ...grpc.CallOption) (*InventoryReply, error)
	GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*InventoryReply, error)
}

type inventoryClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryClient(cc grpc.ClientConnInterface) InventoryClient {
	return &inventoryClient{cc}
}

func (c *inventoryClient) CreateOrReplaceInventory(ctx context.Context, in *CreateOrReplaceInventoryRequest, opts ...grpc.CallOption) (*InventoryReply, error) {
	out := new(InventoryReply)
	err := c.cc.Invoke(ctx, Inventory_CreateOrReplaceInventory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) DeductInventory(ctx context.Context, in *DeductInventoryRequest, opts ...grpc.CallOption) (*InventoryOperationReply, error) {
	out := new(InventoryOperationReply)
	err := c.cc.Invoke(ctx, Inventory_DeductInventory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) IncreaseInventory(ctx context.Context, in *IncreaseInventoryRequest, opts ...grpc.CallOption) (*InventoryOperationReply, error) {
	out := new(InventoryOperationReply)
	err := c.cc.Invoke(ctx, Inventory_IncreaseInventory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) ConfirmInventory(ctx context.Context, in *ConfirmInventoryRequest, opts ...grpc.CallOption) (*InventoryOperationReply, error) {
	out := new(InventoryOperationReply)
	err := c.cc.Invoke(ctx, Inventory_ConfirmInventory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) EditInventory(ctx context.Context, in *EditInventoryRequest, opts ...grpc.CallOption) (*InventoryReply, error) {
	out := new(InventoryReply)
	err := c.cc.Invoke(ctx, Inventory_EditInventory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*InventoryReply, error) {
	out := new(InventoryReply)
	err := c.cc.Invoke(ctx, Inventory_GetInventory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServer is the server API for Inventory service.
// All implementations must embed UnimplementedInventoryServer
// for forward compatibility
type InventoryServer interface {
	CreateOrReplaceInventory(context.Context, *CreateOrReplaceInventoryRequest) (*InventoryReply, error)
	DeductInventory(context.Context, *DeductInventoryRequest) (*InventoryOperationReply, error)
	IncreaseInventory(context.Context, *IncreaseInventoryRequest) (*InventoryOperationReply, error)
	ConfirmInventory(context.Context, *ConfirmInventoryRequest) (*InventoryOperationReply, error)
	EditInventory(context.Context, *EditInventoryRequest) (*InventoryReply, error)
	GetInventory(context.Context, *GetInventoryRequest) (*InventoryReply, error)
	mustEmbedUnimplementedInventoryServer()
}

// UnimplementedInventoryServer must be embedded to have forward compatible implementations.
type UnimplementedInventoryServer struct {
}

func (UnimplementedInventoryServer) CreateOrReplaceInventory(context.Context, *CreateOrReplaceInventoryRequest) (*InventoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrReplaceInventory not implemented")
}
func (UnimplementedInventoryServer) DeductInventory(context.Context, *DeductInventoryRequest) (*InventoryOperationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeductInventory not implemented")
}
func (UnimplementedInventoryServer) IncreaseInventory(context.Context, *IncreaseInventoryRequest) (*InventoryOperationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncreaseInventory not implemented")
}
func (UnimplementedInventoryServer) ConfirmInventory(context.Context, *ConfirmInventoryRequest) (*InventoryOperationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmInventory not implemented")
}
func (UnimplementedInventoryServer) EditInventory(context.Context, *EditInventoryRequest) (*InventoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditInventory not implemented")
}
func (UnimplementedInventoryServer) GetInventory(context.Context, *GetInventoryRequest) (*InventoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInventory not implemented")
}
func (UnimplementedInventoryServer) mustEmbedUnimplementedInventoryServer() {}

// UnsafeInventoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServer will
// result in compilation errors.
type UnsafeInventoryServer interface {
	mustEmbedUnimplementedInventoryServer()
}

func RegisterInventoryServer(s grpc.ServiceRegistrar, srv InventoryServer) {
	s.RegisterService(&Inventory_ServiceDesc, srv)
}

func _Inventory_CreateOrReplaceInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrReplaceInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).CreateOrReplaceInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_CreateOrReplaceInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).CreateOrReplaceInventory(ctx, req.(*CreateOrReplaceInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_DeductInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).DeductInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_DeductInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).DeductInventory(ctx, req.(*DeductInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_IncreaseInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncreaseInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).IncreaseInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_IncreaseInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).IncreaseInventory(ctx, req.(*IncreaseInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_ConfirmInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).ConfirmInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_ConfirmInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).ConfirmInventory(ctx, req.(*ConfirmInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_EditInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).EditInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_EditInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).EditInventory(ctx, req.(*EditInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_GetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).GetInventory(ctx, req.(*GetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Inventory_ServiceDesc is the grpc.ServiceDesc for Inventory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inventory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.Inventory",
	HandlerType: (*InventoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrReplaceInventory",
			Handler:    _Inventory_CreateOrReplaceInventory_Handler,
		},
		{
			MethodName: "DeductInventory",
			Handler:    _Inventory_DeductInventory_Handler,
		},
		{
			MethodName: "IncreaseInventory",
			Handler:    _Inventory_IncreaseInventory_Handler,
		},
		{
			MethodName: "ConfirmInventory",
			Handler:    _Inventory_ConfirmInventory_Handler,
		},
		{
			MethodName: "EditInventory",
			Handler:    _Inventory_EditInventory_Handler,
		},
		{
			MethodName: "GetInventory",
			Handler:    _Inventory_GetInventory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/v1/inventory.proto",
}
