// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: inventory/v1/inventory.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrReplaceInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         int64                  `protobuf:"varint,1,opt,name=sku_id,proto3" json:"sku_id,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrReplaceInventoryRequest) Reset() {
	*x = CreateOrReplaceInventoryRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrReplaceInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrReplaceInventoryRequest) ProtoMessage() {}

func (x *CreateOrReplaceInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrReplaceInventoryRequest.ProtoReflect.Descriptor instead.
func (*CreateOrReplaceInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrReplaceInventoryRequest) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CreateOrReplaceInventoryRequest) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeductInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,proto3" json:"request_id,omitempty"`
	SkuId         int64                  `protobuf:"varint,2,opt,name=sku_id,proto3" json:"sku_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductInventoryRequest) Reset() {
	*x = DeductInventoryRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductInventoryRequest) ProtoMessage() {}

func (x *DeductInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductInventoryRequest.ProtoReflect.Descriptor instead.
func (*DeductInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *DeductInventoryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeductInventoryRequest) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *DeductInventoryRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type IncreaseInventoryRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestId          string                 `protobuf:"bytes,1,opt,name=request_id,proto3" json:"request_id,omitempty"`
	DeductionRequestId string                 `protobuf:"bytes,2,opt,name=deduction_request_id,proto3" json:"deduction_request_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IncreaseInventoryRequest) Reset() {
	*x = IncreaseInventoryRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseInventoryRequest) ProtoMessage() {}

func (x *IncreaseInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseInventoryRequest.ProtoReflect.Descriptor instead.
func (*IncreaseInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *IncreaseInventoryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *IncreaseInventoryRequest) GetDeductionRequestId() string {
	if x != nil {
		return x.DeductionRequestId
	}
	return ""
}

type ConfirmInventoryRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestId          string                 `protobuf:"bytes,1,opt,name=request_id,proto3" json:"request_id,omitempty"`
	DeductionRequestId string                 `protobuf:"bytes,2,opt,name=deduction_request_id,proto3" json:"deduction_request_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfirmInventoryRequest) Reset() {
	*x = ConfirmInventoryRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmInventoryRequest) ProtoMessage() {}

func (x *ConfirmInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmInventoryRequest.ProtoReflect.Descriptor instead.
func (*ConfirmInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmInventoryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfirmInventoryRequest) GetDeductionRequestId() string {
	if x != nil {
		return x.DeductionRequestId
	}
	return ""
}

type EditInventoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SkuId           int64                  `protobuf:"varint,1,opt,name=sku_id,proto3" json:"sku_id,omitempty"`
	Total           int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,3,opt,name=expected_version,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EditInventoryRequest) Reset() {
	*x = EditInventoryRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditInventoryRequest) ProtoMessage() {}

func (x *EditInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditInventoryRequest.ProtoReflect.Descriptor instead.
func (*EditInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *EditInventoryRequest) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *EditInventoryRequest) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *EditInventoryRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         int64                  `protobuf:"varint,1,opt,name=sku_id,proto3" json:"sku_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *GetInventoryRequest) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

type InventoryDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         int64                  `protobuf:"varint,1,opt,name=sku_id,proto3" json:"sku_id,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Available     int64                  `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	Locked        int64                  `protobuf:"varint,4,opt,name=locked,proto3" json:"locked,omitempty"`
	Sold          int64                  `protobuf:"varint,5,opt,name=sold,proto3" json:"sold,omitempty"`
	Version       int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryDTO) Reset() {
	*x = InventoryDTO{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryDTO) ProtoMessage() {}

func (x *InventoryDTO) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryDTO.ProtoReflect.Descriptor instead.
func (*InventoryDTO) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *InventoryDTO) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *InventoryDTO) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *InventoryDTO) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *InventoryDTO) GetLocked() int64 {
	if x != nil {
		return x.Locked
	}
	return 0
}

func (x *InventoryDTO) GetSold() int64 {
	if x != nil {
		return x.Sold
	}
	return 0
}

func (x *InventoryDTO) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeductionDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,proto3" json:"request_id,omitempty"`
	SkuId         int64                  `protobuf:"varint,2,opt,name=sku_id,proto3" json:"sku_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductionDTO) Reset() {
	*x = DeductionDTO{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductionDTO) ProtoMessage() {}

func (x *DeductionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductionDTO.ProtoReflect.Descriptor instead.
func (*DeductionDTO) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *DeductionDTO) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeductionDTO) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *DeductionDTO) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *DeductionDTO) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type InventoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *InventoryDTO          `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReply) Reset() {
	*x = InventoryReply{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReply) ProtoMessage() {}

func (x *InventoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReply.ProtoReflect.Descriptor instead.
func (*InventoryReply) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *InventoryReply) GetInventory() *InventoryDTO {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type InventoryOperationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *InventoryDTO          `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Deduction     *DeductionDTO          `protobuf:"bytes,2,opt,name=deduction,proto3" json:"deduction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryOperationReply) Reset() {
	*x = InventoryOperationReply{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryOperationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryOperationReply) ProtoMessage() {}

func (x *InventoryOperationReply) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryOperationReply.ProtoReflect.Descriptor instead.
func (*InventoryOperationReply) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *InventoryOperationReply) GetInventory() *InventoryDTO {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *InventoryOperationReply) GetDeduction() *DeductionDTO {
	if x != nil {
		return x.Deduction
	}
	return nil
}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\x1a\x1cgoogle/api/annotations.proto\"O\n" +
	"\x1fCreateOrReplaceInventoryRequest\x12\x16\n" +
	"\x06sku_id\x18\x01 \x01(\x03R\x06sku_id\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"l\n" +
	"\x16DeductInventoryRequest\x12\x1e\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\n" +
	"request_id\x12\x16\n" +
	"\x06sku_id\x18\x02 \x01(\x03R\x06sku_id\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"n\n" +
	"\x18IncreaseInventoryRequest\x12\x1e\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\n" +
	"request_id\x122\n" +
	"\x14deduction_request_id\x18\x02 \x01(\tR\x14deduction_request_id\"m\n" +
	"\x17ConfirmInventoryRequest\x12\x1e\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\n" +
	"request_id\x122\n" +
	"\x14deduction_request_id\x18\x02 \x01(\tR\x14deduction_request_id\"p\n" +
	"\x14EditInventoryRequest\x12\x16\n" +
	"\x06sku_id\x18\x01 \x01(\x03R\x06sku_id\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12*\n" +
	"\x10expected_version\x18\x03 \x01(\x03R\x10expected_version\"-\n" +
	"\x13GetInventoryRequest\x12\x16\n" +
	"\x06sku_id\x18\x01 \x01(\x03R\x06sku_id\"\xa0\x01\n" +
	"\fInventoryDTO\x12\x16\n" +
	"\x06sku_id\x18\x01 \x01(\x03R\x06sku_id\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\x03R\tavailable\x12\x16\n" +
	"\x06locked\x18\x04 \x01(\x03R\x06locked\x12\x12\n" +
	"\x04sold\x18\x05 \x01(\x03R\x04sold\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\"z\n" +
	"\fDeductionDTO\x12\x1e\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\n" +
	"request_id\x12\x16\n" +
	"\x06sku_id\x18\x02 \x01(\x03R\x06sku_id\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"J\n" +
	"\x0eInventoryReply\x128\n" +
	"\tinventory\x18\x01 \x01(\v2\x1a.inventory.v1.InventoryDTOR\tinventory\"\x8d\x01\n" +
	"\x17InventoryOperationReply\x128\n" +
	"\tinventory\x18\x01 \x01(\v2\x1a.inventory.v1.InventoryDTOR\tinventory\x128\n" +
	"\tdeduction\x18\x02 \x01(\v2\x1a.inventory.v1.DeductionDTOR\tdeduction2\xaf\x06\n" +
	"\tInventory\x12\x83\x01\n" +
	"\x18CreateOrReplaceInventory\x12-.inventory.v1.CreateOrReplaceInventoryRequest\x1a\x1c.inventory.v1.InventoryReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/inventories\x12\x81\x01\n" +
	"\x0fDeductInventory\x12$.inventory.v1.DeductInventoryRequest\x1a%.inventory.v1.InventoryOperationReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/inventories/deduct\x12\xa5\x01\n" +
	"\x11IncreaseInventory\x12&.inventory.v1.IncreaseInventoryRequest\x1a%.inventory.v1.InventoryOperationReply\"A\x82\xd3\xe4\x93\x02;:\x01*Z\x1c:\x01*\"\x17/v1/inventories/release\"\x18/v1/inventories/increase\x12\x84\x01\n" +
	"\x10ConfirmInventory\x12%.inventory.v1.ConfirmInventoryRequest\x1a%.inventory.v1.InventoryOperationReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/inventories/confirm\x12v\n" +
	"\rEditInventory\x12\".inventory.v1.EditInventoryRequest\x1a\x1c.inventory.v1.InventoryReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/v1/inventories/{sku_id}\x12q\n" +
	"\fGetInventory\x12!.inventory.v1.GetInventoryRequest\x1a\x1c.inventory.v1.InventoryReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/inventories/{sku_id}B'Z%inventory-service/api/inventory/v1;v1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(*CreateOrReplaceInventoryRequest)(nil), // 0: inventory.v1.CreateOrReplaceInventoryRequest
	(*DeductInventoryRequest)(nil),          // 1: inventory.v1.DeductInventoryRequest
	(*IncreaseInventoryRequest)(nil),        // 2: inventory.v1.IncreaseInventoryRequest
	(*ConfirmInventoryRequest)(nil),         // 3: inventory.v1.ConfirmInventoryRequest
	(*EditInventoryRequest)(nil),            // 4: inventory.v1.EditInventoryRequest
	(*GetInventoryRequest)(nil),             // 5: inventory.v1.GetInventoryRequest
	(*InventoryDTO)(nil),                    // 6: inventory.v1.InventoryDTO
	(*DeductionDTO)(nil),                    // 7: inventory.v1.DeductionDTO
	(*InventoryReply)(nil),                  // 8: inventory.v1.InventoryReply
	(*InventoryOperationReply)(nil),         // 9: inventory.v1.InventoryOperationReply
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	6, // 0: inventory.v1.InventoryReply.inventory:type_name -> inventory.v1.InventoryDTO
	6, // 1: inventory.v1.InventoryOperationReply.inventory:type_name -> inventory.v1.InventoryDTO
	7, // 2: inventory.v1.InventoryOperationReply.deduction:type_name -> inventory.v1.DeductionDTO
	0, // 3: inventory.v1.Inventory.CreateOrReplaceInventory:input_type -> inventory.v1.CreateOrReplaceInventoryRequest
	1, // 4: inventory.v1.Inventory.DeductInventory:input_type -> inventory.v1.DeductInventoryRequest
	2, // 5: inventory.v1.Inventory.IncreaseInventory:input_type -> inventory.v1.IncreaseInventoryRequest
	3, // 6: inventory.v1.Inventory.ConfirmInventory:input_type -> inventory.v1.ConfirmInventoryRequest
	4, // 7: inventory.v1.Inventory.EditInventory:input_type -> inventory.v1.EditInventoryRequest
	5, // 8: inventory.v1.Inventory.GetInventory:input_type -> inventory.v1.GetInventoryRequest
	8, // 9: inventory.v1.Inventory.CreateOrReplaceInventory:output_type -> inventory.v1.InventoryReply
	9, // 10: inventory.v1.Inventory.DeductInventory:output_type -> inventory.v1.InventoryOperationReply
	9, // 11: inventory.v1.Inventory.IncreaseInventory:output_type -> inventory.v1.InventoryOperationReply
	9, // 12: inventory.v1.Inventory.ConfirmInventory:output_type -> inventory.v1.InventoryOperationReply
	8, // 13: inventory.v1.Inventory.EditInventory:output_type -> inventory.v1.InventoryReply
	8, // 14: inventory.v1.Inventory.GetInventory:output_type -> inventory.v1.InventoryReply
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
