// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: inventory/v1/inventory.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationInventoryConfirmInventory = "/inventory.v1.Inventory/ConfirmInventory"
const OperationInventoryCreateOrReplaceInventory = "/inventory.v1.Inventory/CreateOrReplaceInventory"
const OperationInventoryDeductInventory = "/inventory.v1.Inventory/DeductInventory"
const OperationInventoryEditInventory = "/inventory.v1.Inventory/EditInventory"
const OperationInventoryGetInventory = "/inventory.v1.Inventory/GetInventory"
const OperationInventoryIncreaseInventory = "/inventory.v1.Inventory/IncreaseInventory"

type InventoryHTTPServer interface {
	ConfirmInventory(context.Context, *ConfirmInventoryRequest) (*InventoryOperationReply, error)
	CreateOrReplaceInventory(context.Context, *CreateOrReplaceInventoryRequest) (*InventoryReply, error)
	DeductInventory(context.Context, *DeductInventoryRequest) (*InventoryOperationReply, error)
	EditInventory(context.Context, *EditInventoryRequest) (*InventoryReply, error)
	GetInventory(context.Context, *GetInventoryRequest) (*InventoryReply, error)
	IncreaseInventory(context.Context, *IncreaseInventoryRequest) (*InventoryOperationReply, error)
}

func RegisterInventoryHTTPServer(s *http.Server, srv InventoryHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/inventories", _Inventory_CreateOrReplaceInventory0_HTTP_Handler(srv))
	r.POST("/v1/inventories/deduct", _Inventory_DeductInventory0_HTTP_Handler(srv))
	r.POST("/v1/inventories/release", _Inventory_IncreaseInventory0_HTTP_Handler(srv))
	r.POST("/v1/inventories/increase", _Inventory_IncreaseInventory1_HTTP_Handler(srv))
	r.POST("/v1/inventories/confirm", _Inventory_ConfirmInventory0_HTTP_Handler(srv))
	r.PUT("/v1/inventories/{sku_id}", _Inventory_EditInventory0_HTTP_Handler(srv))
	r.GET("/v1/inventories/{sku_id}", _Inventory_GetInventory0_HTTP_Handler(srv))
}

func _Inventory_CreateOrReplaceInventory0_HTTP_Handler(srv InventoryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateOrReplaceInventoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryCreateOrReplaceInventory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateOrReplaceInventory(ctx, req.(*CreateOrReplaceInventoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InventoryReply)
		return ctx.Result(200, reply)
	}
}

func _Inventory_DeductInventory0_HTTP_Handler(srv InventoryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeductInventoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryDeductInventory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeductInventory(ctx, req.(*DeductInventoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InventoryOperationReply)
		return ctx.Result(200, reply)
	}
}

func _Inventory_IncreaseInventory0_HTTP_Handler(srv InventoryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in IncreaseInventoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryIncreaseInventory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.IncreaseInventory(ctx, req.(*IncreaseInventoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InventoryOperationReply)
		return ctx.Result(200, reply)
	}
}

func _Inventory_IncreaseInventory1_HTTP_Handler(srv InventoryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in IncreaseInventoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryIncreaseInventory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.IncreaseInventory(ctx, req.(*IncreaseInventoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InventoryOperationReply)
		return ctx.Result(200, reply)
	}
}

func _Inventory_ConfirmInventory0_HTTP_Handler(srv InventoryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConfirmInventoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryConfirmInventory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ConfirmInventory(ctx, req.(*ConfirmInventoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InventoryOperationReply)
		return ctx.Result(200, reply)
	}
}

func _Inventory_EditInventory0_HTTP_Handler(srv InventoryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EditInventoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryEditInventory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EditInventory(ctx, req.(*EditInventoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InventoryReply)
		return ctx.Result(200, reply)
	}
}

func _Inventory_GetInventory0_HTTP_Handler(srv InventoryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetInventoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryGetInventory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetInventory(ctx, req.(*GetInventoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InventoryReply)
		return ctx.Result(200, reply)
	}
}

type InventoryHTTPClient interface {
	ConfirmInventory(ctx context.Context, req *ConfirmInventoryRequest, opts ...http.CallOption) (rsp *InventoryOperationReply, err error)
	CreateOrReplaceInventory(ctx context.Context, req *CreateOrReplaceInventoryRequest, opts ...http.CallOption) (rsp *InventoryReply, err error)
	DeductInventory(ctx context.Context, req *DeductInventoryRequest, opts ...http.CallOption) (rsp *InventoryOperationReply, err error)
	EditInventory(ctx context.Context, req *EditInventoryRequest, opts ...http.CallOption) (rsp *InventoryReply, err error)
	GetInventory(ctx context.Context, req *GetInventoryRequest, opts ...http.CallOption) (rsp *InventoryReply, err error)
	IncreaseInventory(ctx context.Context, req *IncreaseInventoryRequest, opts ...http.CallOption) (rsp *InventoryOperationReply, err error)
}

type InventoryHTTPClientImpl struct {
	cc *http.Client
}

func NewInventoryHTTPClient(client *http.Client) InventoryHTTPClient {
	return &InventoryHTTPClientImpl{client}
}

func (c *InventoryHTTPClientImpl) ConfirmInventory(ctx context.Context, in *ConfirmInventoryRequest, opts ...http.CallOption) (*InventoryOperationReply, error) {
	var out InventoryOperationReply
	pattern := "/v1/inventories/confirm"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInventoryConfirmInventory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InventoryHTTPClientImpl) CreateOrReplaceInventory(ctx context.Context, in *CreateOrReplaceInventoryRequest, opts ...http.CallOption) (*InventoryReply, error) {
	var out InventoryReply
	pattern := "/v1/inventories"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInventoryCreateOrReplaceInventory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InventoryHTTPClientImpl) DeductInventory(ctx context.Context, in *DeductInventoryRequest, opts ...http.CallOption) (*InventoryOperationReply, error) {
	var out InventoryOperationReply
	pattern := "/v1/inventories/deduct"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInventoryDeductInventory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InventoryHTTPClientImpl) EditInventory(ctx context.Context, in *EditInventoryRequest, opts ...http.CallOption) (*InventoryReply, error) {
	var out InventoryReply
	pattern := "/v1/inventories/{sku_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInventoryEditInventory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InventoryHTTPClientImpl) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...http.CallOption) (*InventoryReply, error) {
	var out InventoryReply
	pattern := "/v1/inventories/{sku_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationInventoryGetInventory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InventoryHTTPClientImpl) IncreaseInventory(ctx context.Context, in *IncreaseInventoryRequest, opts ...http.CallOption) (*InventoryOperationReply, error) {
	var out InventoryOperationReply
	pattern := "/v1/inventories/increase"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInventoryIncreaseInventory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
